// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUpN8441NlX8Ln-U8Qvvtzv59eWB5dU8I',
    appId: '1:1074891077548:web:102dde3c72adb12bca6c09',
    messagingSenderId: '1074891077548',
    projectId: 'ecomarket-c2160',
    authDomain: 'ecomarket-c2160.firebaseapp.com',
    storageBucket: 'ecomarket-c2160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxspkLG4YEABvH0-aTfsZPO-gfIJkGI8',
    appId: '1:1074891077548:android:199fd68cf4086bc8ca6c09',
    messagingSenderId: '1074891077548',
    projectId: 'ecomarket-c2160',
    storageBucket: 'ecomarket-c2160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCClPspR2E4kgCBzFwo78xnflQ7985UKWI',
    appId: '1:1074891077548:ios:4ff2a4b1f1d3400fca6c09',
    messagingSenderId: '1074891077548',
    projectId: 'ecomarket-c2160',
    storageBucket: 'ecomarket-c2160.appspot.com',
    iosBundleId: 'com.example.uno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCClPspR2E4kgCBzFwo78xnflQ7985UKWI',
    appId: '1:1074891077548:ios:b5aeed81b5dddadeca6c09',
    messagingSenderId: '1074891077548',
    projectId: 'ecomarket-c2160',
    storageBucket: 'ecomarket-c2160.appspot.com',
    iosBundleId: 'com.example.uno.RunnerTests',
  );
}
